- examples/common/csi-wekafs-api-secret.yaml
- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/node.go
- pkg/wekafs/wekafs.go
This PR allows automatic reconfiguration of the CSI plugin with the current endpoint addresses of the cluster, crucial for cluster with auto-scaling and auto-healing clusters based in cloud. Please refer to documentation, false by default.
Also, the PR includes counters per API endpoint that will be later exposed in Prometheus metrics.
> feat(CSI-209): automated refresh of API endpoints from cluster

- .github/workflows/pull-request.yaml
Updated the Slack notification message in the GitHub workflow to format the `helm upgrade` command as a code block and to include the package path in the footer.
- Changed `SLACK_MESSAGE` to format the `helm upgrade` command as a code block.
- Updated `SLACK_FOOTER` to include the package path.
Trigger a workflow run and verify the Slack notification format and content.
Improving readability and context of Slack notifications.
---
> chore(deps): put installation slack link in code block

- Dockerfile
- pkg/wekafs/gc.go
- pkg/wekafs/utilities.go
Refactored garbage collection initiation and handling in the WekaFS package for better traceability, logging, and performance.
- Introduced OpenTelemetry tracing to GC functions.
- Improved logging for GC initiation and directory deletion processes.
- Replaced synchronous volume purge with move to trash followed by async GC initiation.
- Enhanced directory deletion using worker pool mechanism to limit concurrent deletions.
- Updated variable names and function names for better clarity.
- Run unit tests available for the `wekafs` package.
- Perform integration testing by deploying in staging environment and monitor logs and traces for GC operations.
- Create dozens of PVCs and load them with thousands of files. Delete all PVCs at once, follow up on garbage collection process
- Improved …
> fix(CSI-224,WEKAPP-417375): race condition on multiple volume deletion in parallel

- charts/csi-wekafsplugin/templates/selinux-policy-machineconfig.yaml
Fixed missing divider between YAML documents when created in loop, causing only last document to be applied.
Added the missing separator
ONLY on OpenShift cluster:
Ensure that when multiple machineConfigLabels are specified in values.yaml, a `50-csi-wekafs-selinux-policy-{label}` is created for each label
> fix(CSI-236): for OCP installations, only 1 machineConfigPolicy was created

- .github/workflows/lint_pr.yaml
This change introduces an additional scope 'WEKAPP-\d+' to the PR title linting configuration in our GitHub workflow. This ensures that PR titles can include the WEKAPP identifier.
- Updated the lint_pr.yaml file to recognize and accept 'WEKAPP-\d+' as a valid scope in PR titles.
- Create a PR with 'WEKAPP-xxx' in the title and verify that the linting workflow does not flag it as invalid.
This update is necessary to allow PRs that include WEKAPP identifiers in their title, facilitating better tracking and categorization of tasks related to the WEKAPP project.
---
> chore(deps): allow WEKAPP tickets in lint

- pkg/wekafs/apiclient/apiclient.go
This PR adds validation functions to check for valid IPv4, IPv6 addresses, and hostnames in the `resetDefaultEndpoints` method and skips endpoints that do not pass validation.
- Introduced `isValidIPv4Address`, `isValidIPv6Address`, and `isValidHostname` functions.
- Updated the `resetDefaultEndpoints` method to utilize these validation functions and skip invalid endpoints.
- Add unit tests to check validation functions with various inputs.
- Test CSI plugin basic sanity in IPv6-enabled Kubernetes cluster against IPv6-only Weka cluster (install, create PVC, create pod)
- This change ensures that IPv6 addresses can be specified in configuration
---
> fix(CSI-226): support IPv6 in APIclient

- charts/csi-wekafsplugin/templates/controllerserver-security-context-constraint.yaml
- charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/templates/nodeserver-security-context-constraint.yaml
- charts/csi-wekafsplugin/values.yaml
This pull request introduces a conditional configuration to enable `hostNetwork` support for the `csi-wekafsplugin` Helm chart. The changes involve adding conditional checks in the templates to apply the `hostNetwork` settings based on the values provided.
- Added conditional statements to `controllerserver-statefulset.yaml` and `nodeserver-daemonset.yaml` to apply `hostNetwork` settings.
- Updated security context constraints templates to allow host networking when the `hostNetwork` value is true.
- Modified port numbers in the `nodeserver-daemonset.yaml` to accommodate the `hostNetwork` setup.
1. Set `hostNetwork: true` in the `values.yaml` file.
2. Deploy the Helm chart.
3. Verify that the necessary resources are deployed with the `hostNetwork` configuration.
This change is motivated …
> feat(CSI-227): allow host networking via configuration

- examples/common/csi-wekafs-api-secret.yaml
- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/wekafs.go
Added support for custom CA certificates in WekaFS CSI driver API client.
- Updated `csi-wekafs-api-secret.yaml` to include a new `caCertificate` field for HTTPS connections with self-signed or untrusted certificates.
- Modified `apiclient.go` to handle custom CA certificates when creating a new API client.
- Updated `wekafs.go` to parse the `caCertificate` from secrets and include it in the credentials.
1. Update the `csi-wekafs-api-secret.yaml` file with a base64-encoded PEM format CA certificate in the `caCertificate` field.
2. Deploy the updated secret to your Kubernetes cluster.
3. Verify that the WekaFS CSI driver can successfully connect to the Weka cluster using HTTPS with the custom CA certificate.
> **NOTE**: for this to be tested, we still need the certificate to match endpoint …
> feat(CSI-253): support custom CA certificate in API secret

- pkg/wekafs/mounter.go
- pkg/wekafs/mountoptions.go
Introduced a new `AsMapKey()` method for `MountOptions` to create version-agnostic map keys.
- Added a new `AsMapKey()` method to the `MountOptions` struct in `mountoptions.go`.
- This method creates a version of the mount options that excludes certain options (currently only `MountOptionSyncOnClose`) to be used as a map key.
- Updated `mounter.go` to use `AsMapKey()` instead of `String()` when accessing or modifying the `mountMap`.
Covered by unit testing
This change allows for more consistent handling of mount options across different versions of the Weka cluster / client. By excluding version-specific options like `MountOptionSyncOnClose` from the map key, we can avoid unnecessary duplication of mounts and ensure that mounts with the same essential options are treated as identical, …
> fix(CSI-241): disregard sync_on_close in mountmap per FS

- charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
Updated metrics configuration for CSI WekaFS Plugin to support separate ports for different components.
- Modified the prometheus.io/port annotation in controllerserver-statefulset.yaml to include separate ports for controller, provisioner, resizer, and snapshotter.
- Updated the metrics port configuration in both controllerserver-statefulset.yaml and nodeserver-daemonset.yaml to use component-specific ports.
- Added new metrics port configurations in values.yaml:
- controllerPort: 9090
- provisionerPort: 9091
- resizerPort: 9092
- snapshotterPort: 9093
- nodePort: 9094
1. Deploy the CSI WekaFS Plugin with metrics enabled.
2. Verify that the prometheus.io/port annotation in the controller pod includes all specified ports.
3. Check that the controller and node server pods are exposing …
> fix(CSI-241): conflict in metrics between node and controller

- pkg/wekafs/apiclient/nfs.go
- pkg/wekafs/apiclient/nfs_test.go
- pkg/wekafs/apiclient/utils.go
Improved NFS client group rule matching to include superset IP networks.
- Added `IsSupersetOf` method to `NfsClientGroupRule` to check if a rule covers a larger IP range.
- Updated `FindNfsClientGroupRulesByFilter` to include rules that are supersets of the query.
- Implemented `GetMaskBits` method for `Network` to calculate CIDR notation.
- Enhanced `ContainsIPAddress` method to handle cases where CIDR parsing fails.
- Added unit tests for the new `IsSupersetOf` functionality.
1. Run the new unit tests in `nfs_test.go`.
2. Test the `FindNfsClientGroupRulesByFilter` function with various IP ranges and ensure it returns both exact matches and superset rules.
3. Verify that the `ContainsIPAddress` method correctly identifies IP addresses within a given network range.
This change improves …
> feat(CSI-244): match subnets if existing in client rule

- charts/csi-wekafsplugin/templates/controllerserver-serviceaccount.yaml
- charts/csi-wekafsplugin/templates/nodeserver-serviceaccount.yaml
- charts/csi-wekafsplugin/values.yaml
Updated image pull secret configuration for CSI WekaFS plugin
- Modified `controllerserver-serviceaccount.yaml` and `nodeserver-serviceaccount.yaml` to use a configurable image pull secret
- Added `imagePullSecret` parameter in `values.yaml` to specify the name of the image pull secret
- Wrapped image pull secret configuration in conditional statements to only apply when specified
1. Deploy the chart with `imagePullSecret` set to an existing secret name
2. Verify that the controller and node service accounts are created with the specified image pull secret
3. Deploy the chart without setting `imagePullSecret`
4. Confirm that no image pull secret is added to the service accounts
This change allows users to specify a custom image pull secret for private registries that require …
> fix(CSI-243): service accounts for CSI plugin assume ImagePullSecret and cause error messages.

- pkg/wekafs/gc.go
- pkg/wekafs/volume.go
Improved error handling in volume garbage collection process.
- Modified `triggerGcVolume` and `moveVolumeToTrash` functions to return errors.
- Updated `Trash` method in `Volume` struct to handle the error returned by `triggerGcVolume`.
- Removed synchronous comment from `triggerGcVolume` as it's no longer relevant.
1. Attempt to trash a volume that requires garbage collection.
2. Verify that any errors during the process are properly propagated and handled.
3. Test scenarios where moving the volume to trash might fail (e.g., permission issues, disk full) and ensure errors are returned.
This change improves error handling and propagation in the volume garbage collection process. By returning errors from `triggerGcVolume` and `moveVolumeToTrash`, we can better detect and respond to issues …
> feat(CSI-239): moveToTrash does not return error to upper layers

- Dockerfile
Optimized Dockerfile for Weka CSI Driver
- Updated the `FROM` statement syntax for the go-builder stage
- Simplified the `locar` binary addition using a single `ADD` command with chmod
- Removed separate `RUN chmod` command for `locar`
1. Build the Docker image using the updated Dockerfile
2. Verify that the image builds successfully without errors
3. Run a container from the built image and ensure all components, especially the `locar` binary, are present and executable
- Improves Dockerfile readability and maintainability
- Reduces the number of layers in the final image by combining commands
- Ensures consistent permissions for the `locar` binary using a single `ADD` command
---
chore(deps): combine chmod with ADD in Dockerfile
chore(deps): fix Dockerfile warning for FROM as
> chore(deps): combine chmod with ADD in Dockerfile

- charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- pkg/wekafs/apiclient/nfs.go
- pkg/wekafs/apiclient/nfs_test.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
Added support for specifying a custom NFS client group name in the WekaFS CSI plugin.
- Introduced a new `clientGroupName` parameter in the plugin configuration.
- Updated the controller and node server templates to include the new `clientGroupName` parameter.
- Modified the `EnsureCsiPluginNfsClientGroup` function to use the specified client group name or default to "WekaCSIPluginClients".
- Updated related functions to pass and use the `clientGroupName` parameter.
1. Deploy the WekaFS CSI plugin with a custom client group name:
```yaml
pluginConfig:
mountProtocol:
clientGroupName: "CustomNFSClientGroup"
```
2. Create a PersistentVolumeClaim and a Pod that uses it.
3. Verify that the NFS client group with the specified name is created and used for managing NFS permissions.
4. Check if …
> feat(CSI-245): allow specifying client group for NFS

- pkg/wekafs/nfsmounter.go
Updated `nfsMounter` to use `AsMapKey()` method for mount options.
Modified the `nfsMounter` struct in `nfsmounter.go` to use the `AsMapKey()` method instead of `String()` when accessing and manipulating the `mountMap`. This change affects the `NewMount` and `unmountWithOptions` functions.
1. Create a new mount using `NewMount` with various mount options.
2. Verify that the mount is correctly added to the `mountMap` using the `AsMapKey()` method.
3. Attempt to unmount using `unmountWithOptions` and ensure the correct mount is accessed and removed from the map.
4. Test with different filesystem names and mount options to ensure consistency.
The `AsMapKey()` method likely provides a more consistent or appropriate key for the `mountMap` than the `String()` method. This change may improve the …
> fix(CSI-241): fix unmountWithOptions to use map key rather than options.String()

- pkg/wekafs/apiclient/utils.go
- pkg/wekafs/apiclient/utils_test.go
- pkg/wekafs/nfsmount.go
Added a new function to determine the node's IP address based on routing to a target host.
- Introduced a new function `GetNodeIpAddressByRouting` in `utils.go` that determines the node's IP address by creating a UDP connection to a target host.
- Updated the `doMount` function in `nfsmount.go` to use the new `GetNodeIpAddressByRouting` function, falling back to `GetNodeIpAddress` if it fails.
- Added unit tests for the new `GetNodeIpAddressByRouting` function in `utils_test.go`.
1. Run the new unit tests in `utils_test.go` to verify the functionality of `GetNodeIpAddressByRouting`.
2. Test the NFS mount process with different network configurations to ensure it correctly determines the node's IP address.
3. Verify that the mount process falls back to the original `GetNodeIpAddress` …
> feat(CSI-249): optimize NFS mounter to use multiple targets

- go.mod
- go.sum
- pkg/wekafs/nodeserver.go
Implemented NodeGetVolumeStats functionality and added new node service capabilities.
- Implemented `NodeGetVolumeStats` method in the `NodeServer` struct.
- Added `getVolumeStats` helper function to fetch filesystem statistics.
- Updated `NewNodeServer` to include new node service capabilities:
- SINGLE_NODE_MULTI_WRITER
- GET_VOLUME_STATS
- VOLUME_CONDITION
1. Mount a Weka volume to a node.
2. Call the `NodeGetVolumeStats` method with the volume ID and path.
3. Verify that the method returns correct capacity, used, and available bytes.
4. Test error cases by providing invalid volume IDs or non-existent paths.
5. Verify that the new node service capabilities are reported correctly.
This change enhances the CSI driver's functionality by implementing volume statistics retrieval. It allows …
> feat(CSI-252): implement kubelet PVC stats

- README.md
- README.md.gotmpl
- charts/csi-wekafsplugin/README.md
- charts/csi-wekafsplugin/README.md.gotmpl
- charts/csi-wekafsplugin/templates/NOTES.txt
- docs/NFS.md
Added documentation for using Weka CSI Plugin with NFS transport and updated links to official documentation.
- Added a new document `docs/NFS.md` detailing the usage of Weka CSI Plugin with NFS transport
- Updated README files to include a link to the new NFS documentation
- Updated links to the official Weka CSI Plugin documentation, changing "appendix" to "appendices" in the URL
- Modified the NOTES.txt file to reflect the updated documentation link
1. Review the new `docs/NFS.md` file for accuracy and completeness
2. Verify that the links in the README files and NOTES.txt are correct and functional
3. Test the Weka CSI Plugin with NFS transport following the instructions in the new documentation
This change provides users with information on using the Weka CSI Plugin with NFS …
> docs(CSI-254): update official docs link in Helm templates and README

- README.md
- README.md.gotmpl
- charts/csi-wekafsplugin/values.yaml
Updated Kubernetes version requirements and CSI sidecar image versions.
- Updated the recommended Kubernetes cluster version to 1.20 or later, with a minimum version of 1.17.
- Upgraded CSI sidecar image versions:
- livenessprobe: v2.12.0 -> v2.14.0
- csi-attacher: v4.5.0 -> v4.7.0
- csi-provisioner: v4.0.0 -> v5.1.0
- csi-node-driver-registrar: v2.10.0 -> v2.12.0
- csi-resizer: v1.9.3 -> v1.12.0
- csi-snapshotter: v6.3.3 -> v8.1.0
1. Deploy the updated chart on a Kubernetes cluster version 1.20 or later.
2. Verify that all CSI components are running correctly with the new sidecar image versions.
3. Test basic CSI operations (e.g., volume provisioning, attaching, and mounting) to ensure compatibility.
This update ensures compatibility with newer Kubernetes versions and takes advantage of …
> chore(deps): update sidecar versions

- README.md
Updated the link to the official documentation to: https://docs.weka.io/appendices/weka-csi-plugin.
> chore(deps): update official documentation URL

- pkg/wekafs/interfaces.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/utilities.go
- pkg/wekafs/wekafsmount.go
fix(CSI-256): replace all references of m.mountPoint with m.getMountPoint()
fix(CSI-256): construct mountPoint to have an IP address
fix(CSI-256): implement AnyMount.locateMountIp()
fix(CSI-256): locate actual mount IP upon unmountWithOptions
fix(CSI-256): add a simple mount refCount logic for NFS
> fix(CSI-256): avoid multiple mounts to same filesystem on same mountpoint

- docs/NFS.md
- pkg/wekafs/interfaces.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/wekafsmounter.go
Added support for scheduling workloads by transport protocol (NFS or WekaFS) using node topology.
- Updated `NFS.md` documentation to include information about scheduling workloads by transport protocol.
- Added constants for NFS and WekaFS data transport types.
- Implemented `getTransport()` method for both NFS and WekaFS mounters.
- Modified `NodeGetInfo` function to include transport type in node topology.
1. Deploy the updated Weka CSI Plugin in a hybrid cluster having both nodes with weka client installed and not installed, while setting `pluginConfig.mountProtocol.allowNfsFailback=true`
2. Create a PVC and a pod with a nodeSelector specifying the desired transport:
```yaml
nodeSelector:
topology.weka.com/transport: wekafs
```
or
```yaml
nodeSelector:
topology.weka.com/transport: nfs …
```
> feat(CSI-259): report mount transport in node topology

- pkg/wekafs/apiclient/interfacegroup.go
- pkg/wekafs/apiclient/interfacegroup_test.go
- pkg/wekafs/apiclient/nfs.go
- pkg/wekafs/apiclient/nfs_test.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
Improved NFS interface group handling and error reporting in the WekaFS API client.
- Refactored the `fetchNfsInterfaceGroup` function to handle default and named interface groups more efficiently.
- Added more specific error messages for different scenarios.
- Implemented sorting of IP addresses for consistency.
- Updated the `GetNfsInterfaceGroup` function to use a `useDefault` flag for better control.
1. Test fetching a default NFS interface group without specifying a name.
2. Test fetching a specific NFS interface group by name.
3. Verify error handling for non-existent interface groups.
This change fixes a situation where empty interface group name did not return ANY interface group rather than first matching criteria
> fix(CSI-260): lookup of NFS interface group fails when empty name provided

- docs/NFS.md
- examples/common/csi-wekafs-api-secret.yaml
- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/interfacegroup.go
- pkg/wekafs/wekafs.go
Added support for NFS target IPs in cloud deployments where setting Group IP addresses is not possible.
- Updated `NFS.md` documentation to include information about Weka cluster preparation for NFS access and the new `nfsTargetIps` parameter.
- Modified `csi-wekafs-api-secret.yaml` to include the `nfsTargetIps` field in the API secret.
- Updated `apiclient.go` to include `NfsTargetIPs` in the `Credentials` struct.
- Modified `interfacegroup.go` to use the provided NFS target IPs when available.
- Updated `wekafs.go` to parse and handle the new `nfsTargetIps` parameter from secrets.
1. Deploy the Weka CSI Plugin with NFS failback.
2. Configure the `nfsTargetIps` parameter in the API secret with a comma-separated list of NFS target IP addresses.
3. Create and mount a PVC volume using the …
> feat(CSI-268): support NFS target IPs override via API secret

- pkg/wekafs/apiclient/nfs.go
- pkg/wekafs/controllerserver.go
- pkg/wekafs/interfaces.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/wekafsmount.go
fix(CSI-269): nfsmount mountPoint may be incorrect in certain cases
fix(deps): handle errors in NodeGetVolumeStats() for sanity
refactor(CSI-269): change NFS mount refcount logic and add mount retries
> fix(CSI-269): nfsmount mountPoint may be incorrect in certain cases

- .github/workflows/sanity.yaml
- pkg/wekafs/apiclient/filesystem.go
- tests/csi-sanity/_docker_run_sanity.sh
- tests/csi-sanity/docker-compose-nfs-snapshotcaps.yaml
- tests/csi-sanity/docker-compose.yaml
- tests/csi-sanity/ga-Dockerfile
- tests/csi-sanity/ga_docker_run_sanity.sh
- tests/csi-sanity/wekafs-snapvol.yaml
Added NFS support to CSI sanity tests and improved secret handling in GitHub Actions workflow.
- Added a new job `directory_volume_and_snapshots_nfs` to the GitHub Actions workflow
- Created a new Docker Compose file `docker-compose-nfs-snapshotcaps.yaml` for NFS-specific tests
- Updated the main Docker Compose file to include NFS-enabled plugin services
- Added a new function `directory_volume_and_snapshots_nfs()` to the sanity test script
1. Run the updated GitHub Actions workflow
2. Verify that the new `directory_volume_and_snapshots_nfs` job completes successfully
3. Check the logs for the NFS-specific tests to ensure they're running as expected
4. Confirm that the secret handling steps are working correctly by examining the workflow logs
This change introduces NFS support to the CSI …
> ci(CSI-213): add NFS sanity

- pkg/wekafs/mountoptions.go
Removed "rdirplus" from default NFS mount options.
Modified the `AsNfs()` function in `pkg/wekafs/mountoptions.go` to initialize the `ret` variable with only the "hard" option instead of "hard,rdirplus".
1. Configure Weka CSI plugin to using NFS protocol.
2. Create and publish a `snapshot-backed` PVC
3. Attach the PVC to a pod (via NFS) and ensure no `stale file handle` error occurs when accessing the volume contents from within the pod.
The "rdirplus" option is an optimization that currently is not supported in conjunction with bind mount inside `.snapshots` directory
> fix(CSI-273): remove rdirplus from mountoptions

- pkg/wekafs/apiclient/nfs.go
Enhanced NFS permission handling and version matching in the WekaFS API client.
- Implemented a `Matches` method for `NfsPermission` to compare permissions.
- Modified `FindNfsPermissionsByFilter` to use the new `Matches` method.
- Updated `EnsureNfsPermission` to support both NFSv3 and NFSv4 by default.
1. Create NFS permission having both versions V3 and V4 set on WEKA Cluster. 
2. Attempt to provision a PVC via NFS transport
3. Ensure that provisioning succeeds
This change improves the flexibility and accuracy of NFS permission handling. If a permission exists that allows access via both NFSv3 and NFSv4 (and it matches by all the rest of parameters), the CSI plugin will recognize it and not try to create a duplicate permission
> fix(CSI-275): version of NFS is only set to V4 during NFS permission creation

- pkg/wekafs/nodeserver.go
Improved error handling and logging in the NodeServer implementation.
- Added handling for stale NFS mounts in `NodeUnpublishVolume`.
1. Provision a snapshot-backed PVC and attach it to node on a 2.5.0-beta version of CSI plugin. You might hit a "stale file handle" error that causes the pod to not be able to access the volume contents. In such case, deletion of the pod will fail either.
2. Upgrade the plugin to latest version
3. Unpublish the volume by terminating the pod. Ensure that the PVC is deleted
These changes ensure that pods with mis-attached PVCs (on version 2.5.0-beta2, 2.5.0-beta) may be detached and pods can be terminated. Without the fix, a node reboot might be required to remove the malfunctioning pods.
> fix(CSI-276): allow unpublish even if publish failed with stale file handle

- pkg/wekafs/apiclient/nfs.go
Refactored NFS permission and client group management functions to improve error handling and configuration updates.
- Modified `EnsureNfsPermission` to return a boolean indicating if a new permission was created.
- Updated `EnsureCsiPluginNfsClientGroup` to return a boolean for new group creation.
- Adjusted `EnsureNfsClientGroupRuleForIp` to return a boolean for new rule creation.
- Implemented a configuration update check in `EnsureNfsPermissions` to determine if a wait period is necessary.
- Added a 5-second wait after configuration changes to allow for proper application.
1. Test creating new NFS permissions, client groups, and rules.
2. Verify that existing configurations are not modified unnecessarily.
3. Ensure that the 5-second wait is only applied when new configurations are …
> fix(CSI-274): add sleep before mount if nfs was reconfigured

- pkg/wekafs/controllerserver.go
- pkg/wekafs/identityserver.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/server.go
Removed `trace.WithNewRoot()` from OpenTelemetry span creation and added tracing to GRPC requests.
- Removed `trace.WithNewRoot()` parameter from all `otel.Tracer(TracerName).Start()` calls across multiple files.
- Added OpenTelemetry tracing to GRPC requests in the `logGRPC` function.
- Updated the context in `logGRPC` to include trace and span IDs.
1. Run the CSI driver with OpenTelemetry tracing enabled.
2. Perform various CSI operations (e.g., CreateVolume, DeleteVolume, NodePublishVolume).
3. Verify that the traces are correctly propagated and that GRPC requests are now included in the trace.
4. Ensure that removing `trace.WithNewRoot()` doesn't negatively impact the existing tracing functionality.
This change improves the tracing capabilities of the CSI driver:
1. Removing …
> chore(deps): add OTEL tracing and span logging for GRPC server

- charts/csi-wekafsplugin/values.yaml
- pkg/wekafs/mountoptions.go
- pkg/wekafs/mountoptions_test.go
- Added comprehensive unit tests for `MountOptions` functionality
- Implemented `GetOptionValue(optstr)` method for `MountOptions`
- Added "rw" and "ro" to the list of mutually exclusive mount options
- Removed automatic mapping of "sync_on_close" to "sync" in NFS conversion
- Updated default NFS mount options to include "hard" and "async"
> feat(CSI-282): make async default for NFS mounts

- docs/NFS.md
- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/cluster.go
- pkg/wekafs/nfsmount.go
feat(CSI-288): validate API user role prior to performing ops
- Implement user role and organization ID validation for API client
- Add checks for sufficient CSI permissions
- Prevent NFS mounts for non-Root organizations
docs(CSI-288): add limitation for NFS on Root organization only
- Update NFS documentation to clarify that NFS transport is only available for filesystems in the Root organization
> feat(CSI-288): validate API user role prior to performing ops

- pkg/wekafs/wekafs.go
Improved handling of `localContainerName` in the `fromSecrets` function.
- Modified the `fromSecrets` function in `pkg/wekafs/wekafs.go`.
- Added trimming of whitespace and newline characters from `localContainerName`.
- Restructured the conditional logic for handling the presence of `localContainerName` in secrets.
1. Provide secrets with `localContainerName` containing leading/trailing whitespace or newline characters, e.g. when the string is encoded into Base64 together with a trailing newline
2. Call the `fromSecrets` function with these secrets.
3. Verify that the resulting `localContainerName` is properly trimmed.
4. Test with and without `localContainerName` in the secrets to ensure correct behavior in both cases.
This change improves the robustness of the `fromSecrets` function by …
> feat(CSI-286): whitespace not trimmed for localContainerName in CSI secret

- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
Added a node labeling step to the nodeserver daemonset initialization process.
Modified the init container's command in the nodeserver daemonset to include a step that removes the `topology.csi.weka.io/transport` label from the node before fetching and storing the node metadata.
1. Deploy the updated chart with allowNfsFailback = true (without weka client installed on node)
2. Verify that nodes are labeled with "topology.csi.weka.io/transport" set to "nfs"
3. Ensure that the node has a running weka client and restart the node. The label should set to "wekafs"
This change prepares nodes for potential topology-change operations in the CSI WekaFS plugin. Since CSI cannot modify existing labels upon node registration, having to remove the existing label prior to setting up a new one
> fix(CSI-296): node registration fails after switch transport from NFS to Wekafs due to label conflict

- charts/csi-wekafsplugin/templates/_merge.tpl
- charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
Added support for component-specific affinity and nodeSelector configurations in the CSI WekaFS plugin chart.
- Introduced new `affinity` and `nodeSelector` fields for both controller and node components.
- Updated the controllerserver-statefulset.yaml and nodeserver-daemonset.yaml templates to use these new configurations.
- Added a new `_merge.tpl` file with utility functions for merging configurations.
- Modified the values.yaml file to include the new configuration options.
1. Update the chart with the new changes.
2. Deploy the chart with custom affinity and nodeSelector configurations for controller and node components.
3. Verify that the pods are scheduled according to the specified affinity and nodeSelector rules.
4. Test both global and component-specific configurations to ensure …
> feat(CSI-295): add affinity for controller and separated nodeSelector for controller and node

- Dockerfile
- Makefile
feat(CSI-300): change Makefile to use docker buildx
- Updated Makefile to use `docker buildx build` instead of `docker build`
feat(CSI-300): change Dockerfile to use TARGETOS, TARGETARCH, LOCAR_VERSION, KUBECTL_VERSION
- Added ARG instructions for KUBECTL_VERSION, TARGETARCH, TARGETOS, and LOCAR_VERSION
- Updated Go build command to use TARGETOS and TARGETARCH
- Changed kubectl image to use dynamic KUBECTL_VERSION
- Replaced hardcoded locar download with a more flexible approach using LOCAR_VERSION, TARGETOS, and TARGETARCH
- Moved locar binary copy from ADD instruction to COPY from go-builder stage
> feat(CSI-301): bump locar to version 0.4.2

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
Changed the Controller Server from a StatefulSet to a Deployment.
- Modified the `kind` from `StatefulSet` to `Deployment`
- Removed the `serviceName` field, which is specific to StatefulSets
1. Apply the updated Helm chart
2. Verify that the Controller Server is now running as a Deployment instead of a StatefulSet
3. Ensure that the Controller Server functions correctly in its new configuration
Switching from a StatefulSet to a Deployment provides more flexibility and easier management for the Controller Server. Deployments are better suited for stateless applications and offer simpler scaling and update strategies. This change likely aims to improve the overall performance and maintainability of the CSI WekaFS Plugin.
> feat(CSI-302): convert controller StatefulSet to Deployment

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/values.yaml
Added support for attacher metrics and leader election configuration in the CSI WekaFS plugin.
- Added `configureAttacherLeaderElection` option in the controller section of `values.yaml`
- Included attacher metrics port (default 9095) in the Prometheus annotations
- Updated the csi-attacher container configuration in the controller deployment:
- Added conditional leader election flags
- Added HTTP endpoint for metrics
- Included liveness probe for leader election health check
- Added `attacherPort` (default 9095) to the metrics section in `values.yaml`
1. Deploy the chart with `controller.configureAttacherLeaderElection` set to true
2. Verify that the attacher container in the controller deployment has the leader election flags and liveness probe
3. Check if the Prometheus annotations …
> feat(CSI-303): add livenessProbe to attacher sidecar

- .github/workflows/pull-request.yaml
- .github/workflows/push-dev.yaml
- .github/workflows/release.yaml
- README.md.gotmpl
Added multi-architecture support for AMD64 and ARM64 platforms in Docker builds and updated GitHub Actions workflows.
- Added QEMU setup in GitHub Actions workflows for multi-architecture support
- Included `platforms: linux/amd64,linux/arm64` in Docker build steps
- Updated README to mention support for both AMD64 and ARM64 platforms
- Made minor formatting improvements in workflow files
1. Build the Docker image for both AMD64 and ARM64 platforms
2. Verify that the image can be pulled and run on both architectures
3. Deploy the Helm chart on a Kubernetes cluster with mixed AMD64 and ARM64 nodes
4. Ensure that the CSI driver functions correctly on both architectures
This change expands the compatibility of the CSI WekaFS Plugin to support ARM64 architecture, in addition to the existing …
> feat(CSI-300): add arm64 support

- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/cluster.go
- pkg/wekafs/interfaces.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/utilities.go
- pkg/wekafs/utilities_test.go
- pkg/wekafs/wekafsmount.go
- pkg/wekafs/wekafsmounter.go
Refactored mount handling to improve container name management and mount reference counting.
- Added container name caching to ApiClient
- Introduced `EnsureLocalContainer` method to handle container name resolution
- Simplified mount reference counting using a flat map structure
- Added utility function to extract container names from mount points
- Fixed duplicate reference count increment in NFS mounting
- Added comprehensive test coverage for container name extraction
- Improved logging for mount operations and debugging
1. Test mounting filesystems with different container configurations
2. Verify container name extraction from mount points using the new test cases
3. Check mount reference counting behavior with multiple mount/unmount operations
4. Validate logging output for mount …
> refactor(CSI-305): change mount Map logic for WEKAFS to align with NFS and support same fs name on SCMC

- README.md
- README.md.gotmpl
Added clarification about ARM64 platform support and NFS failback mode in the README
- Updated platform support documentation to specify that ARM64 support starts from version 2.6.0
- Added reference to WEKA documentation for ARM64 support status
- Introduced information about NFS failback mode for unsupported platforms
- Added link to NFS documentation for transport configuration
1. Review the updated README.md
2. Verify links to documentation are working:
- WEKA documentation revision history
- NFS documentation
To provide clearer guidance about platform compatibility and offer alternative solutions through NFS failback mode for users on unsupported platforms. This helps users better understand their deployment options based on their infrastructure.
> docs(CSI-300): improve documentation on ARM support and add links

- pkg/wekafs/controllerserver.go
- pkg/wekafs/mountoptions.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/volume.go
- pkg/wekafs/volumeconstructors.go
feat(CSI-310): drop container_name mount option from volume context
Prevents container_name from being propagated via volume context and removes it if explicitly set in StorageClass mountOptions. The container_name parameter should only be set via API secret.
feat(CSI-310): drop container_name mount option from volume context
feat(CSI-310): drop container_name if explicitly set in SC mountOptions
> feat(CSI-310): drop container_name mount option from volume context

- cmd/wekafsplugin/main.go
- pkg/wekafs/controllerserver.go
- pkg/wekafs/driverconfig.go
Added CSI driver version tracking to provisioned volumes
- Added CSI version to volume context during volume creation
- Introduced version tracking in driver configuration
- Exposed version information through new `GetVersion()` method
1. Deploy the CSI driver
2. Create a new PVC
3. Verify that the provisioned volume includes the `provisionedByCsiVersion` parameter in its volume context
This change enables tracking which CSI driver version was used to provision volumes, making it easier to troubleshoot version-specific issues and manage volume compatibility across driver updates.
> feat(CSI-311): add CSI driver version used for provisioning a PV into volumeContext

- .github/workflows/pull-request.yaml
- .github/workflows/push-dev.yaml
- .github/workflows/release.yaml
- Dockerfile
Added standardized container labels and version metadata to container images
- Added version and release labels to container images in GitHub workflows
- Enhanced Dockerfile with standardized labels including maintainer, name, vendor, summary, description, and URL
- Maintained existing revision and expiration labels
1. Build the container image
2. Inspect the image labels using `docker inspect <image>`
3. Verify all new labels are present and populated correctly:
- version
- release
- maintainer
- name
- vendor
- summary
- description
- url
Standardized container labels improve container discoverability, provide better metadata for container registries, and ensure consistent versioning information across deployments. This helps with container management, auditing, and compliance …
> chore(deps): add labels to CSI Docker image

- pkg/wekafs/controllerserver.go
Added topology support to volume creation in WekaFS CSI driver
- Added `AccessibleTopology` field to volume creation responses
- Implemented `generateAccessibleTopology()` function that creates topology segments with Weka-specific labels
- Applied topology information consistently across all volume creation scenarios
1. Deploy the CSI driver in a Kubernetes cluster with WekaFS
2. Create a new PersistentVolumeClaim (PVC)
3. Verify that the created PV includes topology information
4. Confirm that pods using the PVC are scheduled correctly based on topology constraints
Topology support enables better control over pod scheduling by ensuring pods are scheduled on nodes that have access to WekaFS. This improves the reliability of storage operations and helps maintain proper storage …
> feat(CSI-312): add topology awareness by providing accessibleTopology in PV creation

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
Added support for custom labels on controller and node components in the WekaFS CSI plugin Helm chart.
- Added ability to specify custom labels for the controller deployment and its pods through `controller.labels` and `controller.podLabels`
- Added ability to specify custom labels for the node daemonset and its pods through `node.labels` and `node.podLabels`
- Enhanced selector labels consistency by adding component and release labels
1. Deploy the chart with custom labels:
```yaml
controller:
labels:
custom-label: value1
podLabels:
pod-label: value2
node:
labels:
custom-label: value3
podLabels:
pod-label: value4
```
2. Verify the labels are applied:
```bash
kubectl get deployment -l custom-label=value1
kubectl get pods -l pod-label=value2
kubectl get daemonset -l custom-label=value3 …
```
> feat(CSI-321): provide ability to add custom labels to CSI components

- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/interfacegroup.go
- pkg/wekafs/apiclient/interfacegroup_test.go
- pkg/wekafs/apiclient/nfs.go
- pkg/wekafs/apiclient/nfs_test.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/wekafs.go
Refactored NFS client group registration and management to improve performance and reduce API calls
- Added `NfsInterfaceGroupName` and `NfsClientGroupName` fields to ApiClient struct
- Introduced new `RegisterNfsClientGroup` method to handle NFS client registration
- Simplified NFS mount IP retrieval by removing redundant parameter
- Moved NFS client group registration logic to API client initialization
- Updated related test cases to reflect new structure
1. Clean up the WEKA cluster to make sure no CSI NFS ClientGroup exists.
2. Deploy CSI driver with NFS enabled
3. Create a PVC
4. Verify NFS client group is automatically registered
5. Verify mount operations succeed with proper permissions
5. Run updated test suite: `TestNfsClientGroup`, `TestEnsureCsiPluginNfsClientGroup`, and …
> refactor(CSI-272): move NFS client registration to APIClient startup rather than on each mount

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/volume.go
- pkg/wekafs/volumeconstructors.go
Added a new flag `waitForObjectDeletion` to control whether the CSI driver waits for WEKA filesystem/snapshot deletion completion before acknowledging volume deletion requests.
- Added new `waitForObjectDeletion` configuration flag (defaults to false)
- Modified filesystem and snapshot deletion logic to optionally wait for completion
- Enhanced error messages and logging during deletion operations
- Improved deletion status monitoring and timeout handling
- Fixed potential race conditions in deletion workflows
1. Deploy the CSI driver with `waitForObjectDeletion: true` in the values.yaml
2. Create and then delete a PVC
3. Verify that the deletion operation waits for WEKA filesystem removal
4. Create and delete a PVC and a snapshot
5. Verify that the deletion operation waits for WEKA …
> refactor(CSI-318): add configurable wait for filesystem / snapshot deletion

- Dockerfile
Switch base image from Red Hat UBI to Alpine Linux for the CSI driver container
- Removed UBI_HASH build argument
- Changed base image from `registry.access.redhat.com/ubi9/ubi` to `alpine:3.18`
- Replaced `dnf install` with `apk add` for system packages
- Added additional Alpine-specific packages and CA certificate update step
1. Build the container image using the updated Dockerfile
2. Deploy the CSI driver in a test environment
3. Verify all CSI operations function correctly
4. Confirm system utilities are accessible and working as expected
This is an interim solution to resolve SELinux permissions issues when running on top of SELinux-enabled nodes and using a UBI9 base image.
> fix(CSI-322): revert CSI-309 migrate from Alpine to RedHat UBI9 base image

- pkg/wekafs/volumeconstructors.go
Updated error message when attempting to clone directory-backed volumes without explicitly allowing it in CSI plugin configuration.
Modified the error message when users attempt to clone directory-backed volumes to be more descriptive and helpful, pointing users to documentation for more information.
1. Attempt to clone a directory-backed volume
2. Verify the new error message appears: "Cloning is prohibited for directory-backed volumes, refer to WEKA CSI Plugin documentation for additional information"
The previous error message was unclear and didn't provide users with enough context about why the operation failed or where to find more information. The new message clearly states that directory-backed volumes cannot be cloned and directs users to documentation for further details.
> fix(CSI-323): when snapshot of directory backed volumes is prohibited, incorrect error message is shown stating volume is legacy

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
Updated plugin socket paths to use dynamic release names instead of hardcoded values
- Modified socket directory paths in both controller and node components to use `{{ .Release.Name }}` instead of hardcoded `csi-wekafs`
- Controller path changed from `csi-wekafs-controller` to `{{ .Release.Name }}-controller`
- Node path changed from `csi-wekafs-node` to `{{ .Release.Name }}-node`
1. Deploy the helm chart with a custom release name
2. Verify that the socket directories are created with the correct release name prefix
3. Confirm that the CSI driver can still communicate through the updated socket paths
4. Test volume operations to ensure functionality remains intact
This change enables multiple installations of the CSI driver in the same cluster by using unique socket paths based on the …
> fix(CSI-326): invalid socket dir path causing 2 instances of CSI plugin to interfere with each other

- charts/csi-wekafsplugin/templates/NOTES.txt
- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- examples/dynamic_filesystem_encrypted/README.md
- examples/dynamic_filesystem_encrypted/csi-app-on-fs-clone-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/csi-app-on-fs-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/csi-app-on-fs-snapshot-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/pvc-wekafs-fs-clone-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/pvc-wekafs-fs-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/pvc-wekafs-fs-snapshot-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/snapshot-pvc-wekafs-fs-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted/storageclass-wekafs-fs-encrypted-api.yaml
- examples/dynamic_filesystem_encrypted_nokms/README.md
- examples/dynamic_filesystem_encrypted_nokms/csi-app-on-fs-encrypted-nokms-api.yaml
- examples/dynamic_filesystem_encrypted_nokms/pvc-wekafs-fs-encrypted-nokms-api.yaml
- examples/dynamic_filesystem_encrypted_nokms/storageclass-wekafs-fs-encrypted-nokms-api.yaml
- pkg/wekafs/apiclient/cluster.go
- pkg/wekafs/apiclient/compatibility.go
- pkg/wekafs/apiclient/compatibility_test.go
- pkg/wekafs/apiclient/encryption.go
- pkg/wekafs/apiclient/filesystem.go
- pkg/wekafs/apiclient/kms.go
- pkg/wekafs/apiclient/kms_test.go
- pkg/wekafs/apiclient/quota.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/volume.go
Added support for encrypted filesystems in CSI volumes with and without KMS server configuration.
- Added encryption parameters to filesystem creation API
- Introduced new storage class parameters for encryption configuration:
- `encryptionEnabled`: Enable/disable encryption
- `encryptWithoutKms`: Allow encryption without KMS (testing only)
- Added compatibility checks for encryption features based on WEKA cluster version
- Added example configurations for encrypted filesystem volumes
1. Deploy CSI driver with encryption support enabled
2. Apply the example configurations from either:
- `examples/dynamic_filesystem_encrypted/` for KMS-based encryption
- `examples/dynamic_filesystem_encrypted_nokms/` for testing without KMS
3. Create PVC using the encrypted storage class
4. Verify …
> feat(CSI-315): partial support of encrypted volumes for FS backing

- .github/workflows/pull-request.yaml
- .github/workflows/push-dev.yaml
- .github/workflows/release.yaml
Updated GitHub Actions workflows to use large-runners-public runner group instead of ubuntu-latest
Modified the `runs-on` configuration in pull-request, push-dev, and release workflows to utilize the `large-runners-public` runner group
1. Create a new pull request
2. Verify that workflows are triggered and execute on the large-runners-public group
3. Confirm that all jobs complete successfully
To improve workflow execution performance and resource availability by utilizing larger runner instances instead of the default ubuntu-latest runners
> ci(chore): update workflows to use larger server group

- pkg/wekafs/controllerserver.go
- pkg/wekafs/nodeserver.go
Updated topology labels to support multiple CSI drivers in the same cluster
- Modified topology label generation to include driver-specific labels
- Added local topology labels with driver name prefix
- Maintained global topology labels for backward compatibility
- Updated both controller and node servers to use the new labeling scheme
1. Deploy multiple Weka CSI drivers in the same cluster with different names
2. Create volumes using different CSI drivers
3. Verify that volumes are properly labeled with driver-specific topology
4. Confirm that existing volumes with global topology labels continue to work
To enable running multiple Weka CSI drivers in the same Kubernetes cluster by preventing topology label conflicts between different driver instances. This change maintains backward …
> fix(CSI-329): report volume accessible topology with label corresponding to driver name for multiple instances in large clusters

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
Added configurable termination grace periods for controller and node pods in the WekaFS CSI plugin.
- Added `terminationGracePeriodSeconds` configuration option for both controller and node components
- Set default value to 10 seconds for both components
- Made the value configurable through Helm values
1. Deploy the CSI plugin with custom termination grace periods:
```yaml
controller:
terminationGracePeriodSeconds: 15
node:
terminationGracePeriodSeconds: 20
```
2. Delete a pod and verify it terminates within the configured grace period
3. Verify the default value (10 seconds) is applied when no custom value is specified
To provide more control over pod termination behavior, allowing users to fine-tune how long pods have to gracefully shut down before being forcefully terminated. This …
> fix(CSI-331): add terminationGracePeriodSeconds to controller and pod workloads

- charts/csi-wekafsplugin/templates/selinux-policy-machineconfig.yaml
Updated the MachineConfig name to include the Helm release name in the SELinux policy template.
Modified the `name` field in the MachineConfig template to include `$.Release.Name` as part of the resource identifier, changing from `50-csi-wekafs-selinux-policy-{{ . }}` to `50-{{ $.Release.Name }}-selinux-policy-{{ . }}`.
1. Install the chart with a custom release name
2. Verify that the MachineConfig resources are created with the release name in their names
3. Confirm that SELinux policies are still properly applied to the nodes
This change allows for better resource identification and isolation when multiple instances of the chart are deployed in the same cluster with different release names, preventing potential naming conflicts.
> fix(CSI-332): collision on OCP machineConfigs when installing multiple instances due to same name

- pkg/wekafs/wekafs.go
Added conditional node label cleanup during CSI driver shutdown based on CSI mode.
Modified the termination handler to only perform node label cleanup when the CSI driver is running in Node or All mode. For other modes, the driver now proceeds directly to shutdown without attempting label cleanup.
1. Deploy the CSI driver in different modes (Node, Controller, All)
2. Trigger a shutdown of the driver (e.g., using SIGTERM)
3. Verify that node label cleanup only occurs in Node and All modes
4. Check logs to confirm appropriate shutdown messages
To prevent node label cleanup on controller node, which does not have the necessary permissions and should not set labels.
> fix(CSI-330): label cleanup should be done only on node server

- pkg/wekafs/identityserver.go
- pkg/wekafs/utilities.go
- pkg/wekafs/wekafs.go
Enhanced node readiness checks and label management in the Weka CSI driver
- Added verification of Weka client software connectivity through `/proc/wekafs/interface`
- Implemented automatic node label management based on driver readiness state
- Added new constants for proc paths (`ProcModulesPath` and `ProcWekafsInterface`)
- Enhanced `isWekaInstalled()` to verify both kernel module presence and client software connectivity
- Added `SetNodeLabels()` method to manage node topology labels
1. Deploy the CSI driver in a Kubernetes cluster
2. Verify node labels are automatically set when Weka client is running
3. Verify node labels are removed when Weka client becomes unavailable
4. Check `/proc/wekafs/interface` for "Connected frontend pid" message
5. Monitor node labels for proper topology …
> feat(CSI-337): no readiness check and labels removal when weka client not running

- pkg/wekafs/apiclient/cluster.go
- pkg/wekafs/apiclient/compatibility.go
- pkg/wekafs/apiclient/resolvepath.go
- pkg/wekafs/apiclient/resolvepath_test.go
- pkg/wekafs/volume.go
feat(CSI-340): add resolvePathToInode to compatibility map
feat(CSI-340): implement ApiClient.ResolvePathToInode()
feat(CSI-340): attempt to resolve InodeId from API if supported rather than mount
Adds support for resolving filesystem paths to inodes via API calls for Weka v4.3+ clusters, reducing the need for filesystem mounts. This improves efficiency by eliminating unnecessary mount operations when determining inode IDs.
> feat(CSI-340): use API for inode resolution on path for setting quota

- pkg/wekafs/snapshotconstructors.go
- pkg/wekafs/volume.go
Added caching mechanism for filesystem and snapshot objects to reduce API calls
- Added `fileSystemObject` and `snapshotObject` fields to the Volume struct to cache API responses
- Modified `getFilesystemObj` and `getSnapshotObj` methods to accept a `fromCache` parameter
- Added cache invalidation when deleting filesystems and snapshots
- Updated all method calls to specify whether to use cached objects
1. Create a volume and perform multiple operations on it
2. Monitor API calls to verify reduced number of filesystem/snapshot fetches
3. Verify that cache invalidation works correctly after deletion operations
4. Ensure all volume operations continue to work as expected with caching
The previous implementation made redundant API calls to fetch filesystem and snapshot objects, even when the …
> feat(CSI-341): cache filesystem and snapshot objects to avoid multiple similar API calls

- .github/workflows/lint_pr.yaml
- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/apiclient_test.go
- pkg/wekafs/apiclient/compatibility_test.go
- pkg/wekafs/apiclient/nfs_test.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/wekafsmounter.go
Added validation for empty API endpoints and enhanced encryption compatibility checks.
- Added validation to prevent API client creation when no endpoints are provided
- Added encryption-related compatibility flags for different Weka versions
- Moved API client test setup code to a central location
- Updated mount GC logging to differentiate between transport types
- Made PR scope requirement optional in GitHub workflow
1. Attempt to create an API client with no endpoints - should return error
2. Verify encryption compatibility checks for different Weka versions
3. Run API client tests with provided test credentials
4. Check mount GC logs for both NFS and WekaFS transports
- Prevents potential issues from API clients being created without valid endpoints
- Improves encryption feature …
> fix(CSI-343): panic on apiclient when endpoint list is empty

- pkg/wekafs/identityserver.go
- pkg/wekafs/utilities.go
- pkg/wekafs/wekafs.go
- pkg/wekafs/wekafsmount.go
Changed the check for Weka client from installation to running state and added better error handling for mounts.
- Renamed `isWekaInstalled()` function to `isWekaRunning()` to better reflect its actual purpose
- Added an explicit error check in `doMount()` to verify Weka is running before attempting to mount
- Added a TODO comment to improve the container detection logic
- Updated all references to the renamed function throughout the codebase
1. Test mounting volumes when Weka client is:
- Running normally
- Driver is installed but client is not running (e.g. no container exists)
- Client is stopped via `weka local stop`
- Weka not installed at all on that host
2. Verify appropriate error messages appear when Weka client is not running
3. Confirm NFS failback works correctly when …
> fix(CSI-350): avoid wekafs mounter from mounting if weka is not running

- pkg/wekafs/wekafs.go
Added validation for empty endpoints in the API client creation process.
Added a check in the `fromSecrets` method to verify that the `endpoints` value from the provided secrets is not empty. If empty, the function now returns an error with a clear message indicating that no valid endpoints are defined in the secret.
1. Try to create an API client with an empty endpoints value in the secrets
2. Verify that the function returns the expected error: "no valid endpoints defined in secret, cannot create API client"
3. Test with valid endpoints to ensure normal functionality is preserved
This change improves error handling by providing an early, explicit check for missing endpoints configuration. Without this validation, the code would likely fail later with a less descriptive error message, …
> fix(CSI-351): incorrect error message when creating PVC with CSI secret missing endpoints

- pkg/wekafs/wekafs.go
Added transport type labeling to nodes for WekaFS driver.
- Added a new function to determine the appropriate transport type ("nfs" or "wekafs") based on configuration and system state
- Added a new label to track the transport type using the `TopologyLabelTransportPattern` format
- Added the `TopologyKeyNode` label to the node
1. Deploy the CSI driver with different configurations:
- With `useNfs: true`
- With `allowNfsFailback: true` and Weka not running
- With standard WekaFS configuration
2. Verify that nodes are correctly labeled with the appropriate transport type
3. Check that the `TopologyKeyNode` label is properly set with the node ID
This change enables better scheduling decisions by exposing the transport mechanism (NFS or WekaFS) as a node label. This information can be used …
> fix(CSI-352): topology.csi.weka.io/transport=wekafs & topology.wekafs.csi/node labels missing on weka client restart

- .github/workflows/sanity.yaml
- cmd/wekafsplugin/main.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/volume.go
- pkg/wekafs/volumeconstructors.go
- tests/csi-sanity/docker-compose-nfs-snapshotcaps.yaml
- tests/csi-sanity/docker-compose-snapshotcaps.yaml
- Added `TRACING_SETTING` environment variable to GitHub workflows for configuring tracing in sanity tests
- Added tracing URL to driver configuration and improved logging of tracing initialization
- Enhanced volume creation logs by adding source ID information to debug messages
- Added debug logging when checking for underlying snapshots during volume operations
- Improved volume initialization logging with better context about volume origins
The changes improve observability by propagating tracing configuration from GitHub variables to test environments and adding more detailed logging around critical operations.
> ci: add tracing-configuration-for-sanity

- pkg/wekafs/volume.go
Simplified volume capacity update logic by removing the fallback mechanism and improving logging.
- Removed the fallback mechanism that would try to use xattr if setting quota failed
- Added a `capacityEntity` variable to track which method is being used (quota or xattr)
- Improved logging by including the capacity entity in success and error messages
- Enhanced warning message for non-default organization to suggest upgrading to the latest Weka software
- Streamlined error handling logic to be more consistent
1. Test volume capacity updates in different scenarios:
- With a regular Weka cluster that supports quota
- In in DEV mode
- With a volume that has no API client bound
- With a cluster that doesn't support quota directory as volume
- With a non-default organization
- With a …
> feat(CSI-356): avoid failback to xattr upon quota set error

- pkg/wekafs/mountoptions_test.go
- pkg/wekafs/volume.go
Fixed mount options precedence and enhanced mutually exclusive options handling.
1. Reversed the order of mount options merging in `Volume.MountUnderlyingFS()` to prioritize volume-specific options over server default options
2. Added a new mutually exclusive mount option set for caching-related options: `coherent`, `forcedirect`, `readcache`, and `writecache`.
3. Enhanced the test case for `MountOptions_Merge` to verify the behavior of the new mutually exclusive options.
1. Run the updated unit tests: `go test ./pkg/wekafs -run TestMountOptions_Merge`
2. Verify that when merging mount options, the mutually exclusive options are properly handled (e.g., `writecache` is removed when `forcedirect` is added).
3. Test mounting a volume with conflicting options to ensure the server defaults …
> fix(CSI-357): server default mount options take precedence over custom ones

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- go.mod
- go.sum
- pkg/wekafs/otel.go
Replace Jaeger exporter with OpenTelemetry OTLP gRPC exporter for distributed tracing.
- Replaced the Jaeger exporter dependency (`go.opentelemetry.io/otel/exporters/jaeger`) with OpenTelemetry's OTLP gRPC exporter (`go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc`)
- Updated the `TracerProvider` function in `pkg/wekafs/otel.go` to use the OTLP gRPC exporter instead of Jaeger
- Added a context parameter to the exporter initialization
- Added necessary dependencies in go.mod and go.sum files
1. Configure the application with a valid OTLP endpoint URL
2. Verify that traces are being sent to the configured endpoint
3. Confirm that the application can connect to an OpenTelemetry collector using gRPC protocol
The OpenTelemetry OTLP exporter provides a more standardized approach …
> feat(CSI-317): switch from jaeger to otlptracegrpc

- pkg/wekafs/apiclient/filesystem.go
- pkg/wekafs/volume.go
- pkg/wekafs/volume_test.go
Added support for force-fresh filesystem capacity queries through the API
- Added `ForceFresh` parameter to filesystem API calls to ensure accurate capacity reporting
- Implemented new `getFilesystemFreeSpaceByApi` method to query filesystem capacity directly through API
- Modified `getFilesystemFreeSpace` to prioritize API-based capacity queries when possible
- Added unit tests to verify both capacity query methods
1. Run the new unit tests using:
```bash
go test -v ./pkg/wekafs -args \
-api-endpoint=<your-endpoint> \
-api-username=<username> \
-api-password=<password> \
-api-org=<org> \
-fs-name=<filesystem-name>
```
2. Verify that both `TestVolume_getFilesystemFreeSpaceByApi` and `TestVolume_getFilesystemFreeSpace` pass
3. Confirm that filesystem capacity queries return accurate, …
> feat(CSI-342): get filesystem free space via API without requiring fs mount

- .github/workflows/sanity.yaml
Update Docker Buildx to latest version in the sanity workflow.
Added configuration to the `docker/setup-buildx-action@v3` step in the GitHub workflow to explicitly use the latest version of Buildx.
Run the sanity workflow to verify that the Docker Buildx setup completes successfully with the latest version.
Using the latest version of Buildx ensures we have access to the most recent features and bug fixes, which can improve build performance and reliability in our CI pipeline.
Also it comes to resolve issues with GitHub Actions Cache update to v2
> ci: make sure to use latest docker buildx to support GH cache v2

- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/apiclient_test.go
- pkg/wekafs/apiclient/apiendpoint.go
- pkg/wekafs/apiclient/errors.go
- pkg/wekafs/apiclient/quota.go
- pkg/wekafs/apiclient/requests.go
Improved error handling in the API client by adding support for more error types and enhancing transient error detection.
- Renamed `handleNetworkErrors` to `handleTransientErrors` to better reflect its purpose
- Added handling for additional error types:
- `transportError`
- `ApiInternalError`
- `ApiNotAvailableError`
- Added a new `ApiNotAvailableError` type for HTTP 503 Service Unavailable responses
- Added tracking for HTTP 503 errors in the `ApiEndPoint` struct
- Enhanced error handling in the request method to properly handle different HTTP status codes
- Added comprehensive test cases for various API client error scenarios
Run the new test cases added in `apiclient_test.go`:
```
go test -v ./pkg/wekafs/apiclient -run TestApiClientRequest
```
The tests cover various error scenarios …
> fix(CSI-358): rotation to another API andpoint does not happen on error 503

- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/identityserver.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/volume_test.go
Added a new configuration option to control whether the CSI plugin manages node topology labels.
- Added a new configuration parameter `manageNodeTopologyLabels` (default: true) to control whether the CSI plugin manages node topology labels
- Added a new command-line flag `--managenodetopologylabels` to the plugin
- Modified the Helm chart to expose this configuration option
- Updated the node server and identity server logic to respect this setting
- Added a warning log when topology label management is disabled
1. Deploy the CSI plugin with default settings (labels will be managed)
2. Deploy the CSI plugin with `pluginConfig.manageNodeTopologyLabels: false` and verify that node topology labels are not being managed
3. For Operator-managed clusters, set this value to `false` to avoid …
> feat(CSI-360): make node topology labeling configurable in favor of auxilary management via operator

- charts/csi-wekafsplugin/values.yaml
Updated all CSI sidecar container images to their latest versions.
Updated the following CSI sidecar container images to newer versions:
- livenessprobe: v2.15.0 → v2.16.0
- csi-attacher: v4.8.0 → v4.9.0
- csi-provisioner: v5.1.0 → v5.3.0
- csi-node-driver-registrar: v2.13.0 → v2.14.0
- csi-resizer: v1.13.1 → v1.14.0
- csi-snapshotter: v8.2.0 → v8.3.0
1. Deploy the CSI WekaFS plugin with the updated values
2. Verify that all pods start correctly with the new container images
3. Test basic CSI operations (volume provisioning, mounting, resizing, snapshots) to ensure functionality
Keeping the CSI sidecar containers updated ensures we benefit from the latest bug fixes, security patches, and performance improvements from the Kubernetes storage SIG. These updates help maintain compatibility …
> chore(deps): update sidecars as of 2025-07-27

- .github/workflows/pull-request.yaml
- .github/workflows/sanity.yaml
- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- pkg/wekafs/apiclient/filesystem.go
- pkg/wekafs/controllerserver.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/identityserver.go
- pkg/wekafs/interfaces.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/volume.go
- pkg/wekafs/wekafs.go
Improved CSI plugin latency on DeleteVolume by moving the deletion of actual filesystem and NFS permissions to asynchronous flow. This behavior is configurable via `allowAsyncObjectDeletion` flag.
- Changed GitHub workflow to use standard runners instead of large runners
- Added Docker Compose setup action to all sanity test jobs
- Renamed `waitForObjectDeletion` flag to `allowAsyncObjectDeletion` with inverted logic
- Added background task tracking with WaitGroup to ensure clean shutdown
- Added retry logic (up to 5 attempts with 1-second intervals) when deleting NFS permissions
- Fixed filesystem name typo in logs
- Improved error messages for NFS permission deletion failures
- Updated Helm chart values to reflect the parameter name change
1. Create a volume with NFS transport
2. Delete …
> feat(CSI-344): delete filesystems out-of-band if not waiting for object deletion

- pkg/wekafs/controllerserver.go
- pkg/wekafs/identityserver.go
- pkg/wekafs/interfaces.go
- pkg/wekafs/mountergroup.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/utilities.go
- pkg/wekafs/volume.go
- pkg/wekafs/wekafs.go
- pkg/wekafs/wekafsmounter.go
Adds support for multiple transport protocols (NFS/WekaFS) with automatic failover and protocol preference configuration. Enables dynamic selection of the optimal transport method based on system capabilities and configuration settings.
Key changes:
- Introduces MounterGroup to manage multiple transport protocols
- Implements transport protocol preference ordering
- Adds automatic failover between WekaFS and NFS based on system availability
- Supports configuration-driven transport selection
- Maintains backward compatibility with existing mount paths
- Adds enable/disable functionality for transport protocols
> feat(CSI-334): allow using multiple mounters in parallel on same server

- pkg/wekafs/controllerserver.go
- pkg/wekafs/nodeserver.go
Added default concurrency limit for operations without explicit configuration.
Modified the `initializeSemaphore` method in both `ControllerServer` and `NodeServer` to handle cases where an operation doesn't have a configured concurrency limit. Now, if an operation's concurrency limit is not explicitly set in `maxConcurrencyPerOp`, it defaults to 1 instead of potentially causing issues with an undefined value.
1. Deploy the CSI driver without specifying concurrency limits for some operations
2. Verify that operations without explicit concurrency limits work correctly
3. Check logs to confirm that semaphores are initialized with the default value of 1 for these operations
This change improves robustness by ensuring all operations have a valid concurrency limit, even when not explicitly …
> fix(CSI-335): initializeSemaphore should set 1 for unknown operations

- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
Removed legacy volume secret mount from the nodeserver daemonset.
Removed the conditional mount of the legacy volume secret in the nodeserver daemonset template. Specifically:
- Removed the volume mount at `/legacy-volume-access` from the container spec
- Removed the corresponding volume definition that referenced `legacyVolumeSecretName`
1. Deploy the chart with and without `legacyVolumeSecretName` defined
2. Verify that the nodeserver daemonset no longer attempts to mount the legacy volume secret
3. Ensure that existing functionality works correctly without this mount
This change removes support for a legacy feature that is no longer needed, and complements the removal of legacy volume support
> fix(CSI-371): remove legacy volume secret mount

- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/apiendpoint.go
- pkg/wekafs/apiclient/apiobject.go
- pkg/wekafs/apiclient/cluster.go
- pkg/wekafs/apiclient/errors.go
- pkg/wekafs/apiclient/filesystem.go
- pkg/wekafs/apiclient/interfacegroup.go
- pkg/wekafs/apiclient/kms.go
- pkg/wekafs/apiclient/nfs.go
- pkg/wekafs/apiclient/nfs_test.go
- pkg/wekafs/apiclient/node.go
- pkg/wekafs/apiclient/quota.go
- pkg/wekafs/apiclient/requests.go
- pkg/wekafs/apiclient/resolvepath.go
- pkg/wekafs/apiclient/snapshot.go
- pkg/wekafs/volume.go
Refactored the API client to improve pagination support, endpoint management, and added caching for filesystem objects.
- Restructured `ApiClient` to use a dedicated `ApiEndPoints` type for better endpoint management
- Added pagination support for API responses with a new `ApiObjectResponse` interface
- Implemented filesystem caching to reduce redundant API calls
- Added metrics collection for API requests
- Created a new `ApiClientOptions` struct for more flexible client initialization
- Improved error handling for API requests, including support for paginated responses
- Added support for performance statistics on filesystems and quotas
- Extracted `ApiStore` into its own file for better code organization
1. Verify that API clients can be created with the new `ApiClientOptions` …
> feat(CSI-379): support pagination for REST API client

- pkg/wekafs/apiclient/apiclient.go
- pkg/wekafs/apiclient/apiclient_test.go
- pkg/wekafs/apiclient/login.go
- pkg/wekafs/apiclient/metrics.go
- pkg/wekafs/apiclient/requests.go
- pkg/wekafs/apiclient/utils.go
- pkg/wekafs/apistore.go
Added API metrics collection for the Weka CSI driver to track API requests and performance.
- Created a new `ApiMetrics` struct and implementation in `metrics.go` to collect Prometheus metrics
- Added metrics for tracking:
- Number of API endpoints
- API request counts (broken down by endpoint, method, URL, status)
- API request durations (with histogram buckets)
- Added metrics initialization in the API client's `Init` method
- Implemented request tracking in the `do` method with proper labeling
- Added URL path generalization to prevent cardinality explosion in metrics
1. Deploy the CSI driver with Prometheus enabled
2. Check that the new metrics are being collected:
- `weka_csi_api_endpoints_count`
- `weka_csi_api_request_count`
- `weka_csi_api_request_duration_seconds`
3. Verify …
> feat(CSI-363): implement counters for API endpoints

- charts/csi-wekafsplugin/templates/controllerserver-deployment.yaml
- charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
- charts/csi-wekafsplugin/values.yaml
- cmd/wekafsplugin/main.go
- pkg/wekafs/driverconfig.go
- pkg/wekafs/identityserver.go
- pkg/wekafs/volume_test.go
Added configurable timeout for Weka API requests in the CSI driver.
- Added a new configuration parameter `apiTimeoutSeconds` to control the timeout for Weka API requests
- Set a default value of 60 seconds in the Helm chart values
- Added the `--wekaapitimeoutseconds` flag to both controller and node server deployments
- Updated the driver configuration to store and use this timeout value
- Modified the code to pass this timeout duration to the appropriate components
1. Deploy the CSI driver with a custom API timeout:
```yaml
pluginConfig:
apiTimeoutSeconds: 120
```
2. Verify that the timeout is correctly passed to the controller and node server pods
3. Test operations that interact with the Weka API to ensure they respect the configured timeout
The default API timeout may not be …
> feat(CSI-381): make WEKA API timeout configurable

- pkg/wekafs/anymount.go
- pkg/wekafs/anymounter.go
- pkg/wekafs/gc.go
- pkg/wekafs/interfaces.go
- pkg/wekafs/mountmap.go
- pkg/wekafs/nfsmount.go
- pkg/wekafs/nfsmounter.go
- pkg/wekafs/nodeserver.go
- pkg/wekafs/utilities.go
- pkg/wekafs/utilities_test.go
- pkg/wekafs/volume.go
- pkg/wekafs/wekafsmount.go
- pkg/wekafs/wekafsmounter.go
Refactored mount handling code to reduce duplication between NFS and WekaFS implementations by extracting common functionality into shared methods.
- Created new files `anymount.go` and `anymounter.go` with shared mount handling logic
- Implemented a thread-safe `mountMap` structure to track mount references
- Extracted common mount/unmount functionality into shared methods like `anyMountIncref`, `anyMountDecRef`, and `anyMountDoUnmount`
- Updated `PathIsWekaMount` to remove unnecessary context parameter
- Standardized interfaces for mount operations across different transport types
- Fixed container name handling in WekaFS mounts
- Improved error handling and logging in mount operations
1. Test mounting and unmounting volumes using both NFS and WekaFS transports
2. Verify reference …
> refactor: unify mounters functions and fix refcount issues

- charts/csi-wekafsplugin/values.yaml
Increased concurrency limits for CSI controller operations to improve performance.
- Increased the global `maxConcurrentRequests` from 5 to 25
- Increased concurrency limits for volume operations:
- `createVolume`: 5 → 25
- `deleteVolume`: 5 → 25
- `expandVolume`: 5 → 25
- `createSnapshot`: 5 → 10
- `deleteSnapshot`: 5 → 10
1. Deploy the CSI driver with these updated values
2. Run high-concurrency volume operations (create/delete/expand volumes and snapshots)
3. Verify that the system can handle more concurrent operations without errors
4. Monitor for any potential resource constraints or issues with the higher concurrency
The increased concurrency limits will allow the CSI controller to handle more operations simultaneously, reducing wait times and improving overall performance in …
> chore: increase controller volume operation concurrency

- charts/csi-wekafsplugin/values.yaml
- cmd/metricsserver/main.go
- pkg/wekafs/driver.go
- pkg/wekafs/metricsserver.go
- pkg/wekafs/server.go
Updated the description of `maxConcurrentRequests` parameter and implemented dynamic calculation of gRPC server's `MaxConcurrentStreams`.
- Clarified the description of `maxConcurrentRequests` in the Helm chart values file to indicate it applies "for each sidecar" rather than "global"
- Added logic to dynamically calculate the appropriate value for `MaxConcurrentStreams` in the gRPC server options:
- Sums all maximum concurrency values per operation
- Doubles the result to provide extra capacity for liveness probes and other operations
- Sets a minimum value of 256 if the calculated value is lower
1. Deploy the CSI plugin with various concurrency settings
2. Verify that the gRPC server correctly handles the expected number of concurrent requests
3. Check that under high load, the server …
> fix: readiness probe might fail under load due to too small max concurrency of GRPC server
